/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import cajero.Gestionador;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JTextArea;

/**
 *
 * @author Daniel
 */
public class PanelTransferir extends javax.swing.JPanel {

    /**
     * Creates new form PanelTransferir
     */
    public PanelTransferir(Gestionador gestionador, Container panelOpciones, JTextArea areaTexto, JFrame panelPrincipal) {
        initComponents();
        panelOpciones.remove(0);
        panelOpciones.add(this, BorderLayout.PAGE_START);
        panelOpciones.revalidate();
        panelOpciones.repaint();
        panelPrincipal.pack();

        btnTranferir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String numCuenta = jtfNroCuenta.getText();
                String monto = jtfMontoATransferir.getText();
                boolean transferido = gestionador.transferir(numCuenta, monto);
                if (transferido) {
                    areaTexto.append("Se ha transferido con exito el monto de: " + monto);
                } else {
                    areaTexto.append("A ocurrido un error de transferencia " + monto);
                }
            }

        });

        btnAtras.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PanelOpciones opciones = new PanelOpciones(gestionador,panelPrincipal);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTranferir = new javax.swing.JButton();
        jtfNroCuenta = new javax.swing.JTextField();
        jtfMontoATransferir = new javax.swing.JTextField();
        lblNroCuenta = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();

        btnTranferir.setText("Transferir");

        lblNroCuenta.setText("Ingrese el Nro Cuenta");

        lblMonto.setText("Monto a Transferir");

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMonto)
                            .addComponent(jtfMontoATransferir, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNroCuenta)
                            .addComponent(jtfNroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(btnTranferir)))
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAtras)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jtfNroCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNroCuenta)
                .addGap(18, 18, 18)
                .addComponent(jtfMontoATransferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMonto)
                .addGap(18, 18, 18)
                .addComponent(btnTranferir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnAtras)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnTranferir;
    private javax.swing.JTextField jtfMontoATransferir;
    private javax.swing.JTextField jtfNroCuenta;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNroCuenta;
    // End of variables declaration//GEN-END:variables
}
