/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import cajero.Evento;
import cajero.GestorCuenta;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class PanelCambioContrasena extends javax.swing.JPanel {

    /**
     * Creates new form PanelCambioContrasena
     */
    public PanelCambioContrasena(GestorCuenta gestionador, Container panelOpciones, DefaultTableModel registro, JFrame panelPrincipal) {
        initComponents();
        panelOpciones.remove(0);
        panelOpciones.add(this, BorderLayout.PAGE_START);
        panelOpciones.revalidate();
        panelOpciones.repaint();
        panelPrincipal.pack();

        btnConfirmaCambio.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                char[] antiguaCont = jAntiguaConstrasena.getPassword();
                char[] nuevaCont = jNuevaContrasena.getPassword();
                char[] confirmacionCont = jNuevaContrasenaConfirmacion.getPassword();
                
             
                boolean contrasenaCoincide = gestionador.contrasenaCoincide(antiguaCont);
                boolean nuevaContrasenaCoincide = gestionador.cambiarContrasena(nuevaCont, confirmacionCont);
                if (contrasenaCoincide && nuevaContrasenaCoincide) {
                    lblCambioContrasena.setText("Se cambió la Contrasena con Existo.");
                } else {
                    lblCambioContrasena.setText("No se pudo realizar");
                }
            }

        });

        btnAtras.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {        
                PanelOpciones opciones = new PanelOpciones(gestionador, panelPrincipal);                
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jAntiguaConstrasena = new javax.swing.JPasswordField();
        btnConfirmaCambio = new javax.swing.JButton();
        jNuevaContrasenaConfirmacion = new javax.swing.JPasswordField();
        jNuevaContrasena = new javax.swing.JPasswordField();
        lblConstrasenaAntigua = new javax.swing.JLabel();
        lblNuevaContrasena = new javax.swing.JLabel();
        lblConfirmaNuevaContrasena = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        lblCambioContrasena = new javax.swing.JLabel();

        btnConfirmaCambio.setText("Confirma Cambio");

        lblConstrasenaAntigua.setText("Antigua Contrasena");

        lblNuevaContrasena.setText("Nueva Contrasena");

        lblConfirmaNuevaContrasena.setText("Confirma Nueva Contrasena");

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCambioContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuevaContrasena)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblConstrasenaAntigua)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jAntiguaConstrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnAtras))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnConfirmaCambio)
                        .addComponent(lblConfirmaNuevaContrasena))
                    .addComponent(jNuevaContrasenaConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jAntiguaConstrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lblConstrasenaAntigua))
                    .addComponent(btnAtras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jNuevaContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNuevaContrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jNuevaContrasenaConfirmacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConfirmaNuevaContrasena)
                .addGap(18, 18, 18)
                .addComponent(lblCambioContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btnConfirmaCambio)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnConfirmaCambio;
    private javax.swing.JPasswordField jAntiguaConstrasena;
    private javax.swing.JPasswordField jNuevaContrasena;
    private javax.swing.JPasswordField jNuevaContrasenaConfirmacion;
    private javax.swing.JLabel lblCambioContrasena;
    private javax.swing.JLabel lblConfirmaNuevaContrasena;
    private javax.swing.JLabel lblConstrasenaAntigua;
    private javax.swing.JLabel lblNuevaContrasena;
    // End of variables declaration//GEN-END:variables
}
