/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ventanas;

import cajero.Cuenta;
import cajero.Evento;
import cajero.GestorCuenta;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.util.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class PanelDepositar extends javax.swing.JPanel {

    /**
     * Creates new form PanelDepositar
     */
    public PanelDepositar(String divisa, GestorCuenta gestionador, Container panelOpciones, DefaultTableModel registro, JFrame panelPrincipal) {
        initComponents();
        panelOpciones.remove(1);
        panelOpciones.add(this, BorderLayout.NORTH);
        panelOpciones.revalidate();
        panelOpciones.repaint();
        panelPrincipal.pack();
        lblDivisa.setText(divisa);
        lblMonto.setText(String.format("%.2f", Double.parseDouble(gestionador.saldoDisponible())));
        lblDivisaSaldo.setText(gestionador.getDivisa());

        btnDepositar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                registro.setRowCount(0);
                String monto = jtfMonto.getText();

                if (Double.parseDouble(monto) > 0) {
                    gestionador.depositar(divisa.toLowerCase(), Double.parseDouble(monto));
                    double montoConvertido = gestionador.getMontoConvertido(divisa.toLowerCase(), Double.parseDouble(monto));
       
                    gestionador.crearEvento(new Evento(gestionador.getNroCuenta(), "Se realizó un deposito.", Double.toString(montoConvertido) , gestionador.saldoDisponible()));
                    List<Evento> eventos = gestionador.getEventos();
                    for (int i = 0; i < eventos.size(); i++) {
                        Evento evento = eventos.get(i);
                        String[] filaEvento = new String[4];
                        filaEvento[0] = evento.getFecha();
                        filaEvento[1] = evento.getDescripcion();
                        filaEvento[2] = String.format("%.2f",Double.parseDouble(evento.getMonto()));
                        filaEvento[3] = String.format("%.2f",Double.parseDouble(evento.getSaldo()));
                        registro.addRow(filaEvento);
                    }

                    lblMonto.setText(String.format("%.2f", Double.parseDouble(gestionador.saldoDisponible())));
                    lblAviso.setText("Operacion Exitosa");
                    lblAviso.setForeground(new Color(0, 153, 0));
                }else{
                    lblAviso.setText("Entrada Inválida");
                    lblAviso.setForeground(new Color(204, 0, 0));
                    
                }
            }

        });

        btnAtras.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PanelOpciones panelOpciones = new PanelOpciones(gestionador, panelPrincipal);
            }

        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDepositar = new javax.swing.JButton();
        jtfMonto = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        lblMontoADepositar = new javax.swing.JLabel();
        lblDivisa = new javax.swing.JLabel();
        lblSaldoDisponible = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblDivisaSaldo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblDepositar = new javax.swing.JLabel();
        lblAviso = new javax.swing.JLabel();

        setBackground(new java.awt.Color(134, 190, 225));

        btnDepositar.setBackground(new java.awt.Color(0, 174, 237));
        btnDepositar.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        btnDepositar.setForeground(new java.awt.Color(255, 255, 255));
        btnDepositar.setText("Depositar");

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/atras.png"))); // NOI18N

        lblMontoADepositar.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        lblMontoADepositar.setForeground(new java.awt.Color(255, 255, 255));
        lblMontoADepositar.setText("Monto a Depositar");

        lblDivisa.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        lblDivisa.setForeground(new java.awt.Color(255, 255, 255));

        lblSaldoDisponible.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        lblSaldoDisponible.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldoDisponible.setText("Saldo Disponible");

        lblMonto.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        lblMonto.setForeground(new java.awt.Color(255, 255, 255));
        lblMonto.setText("00000000");

        lblDivisaSaldo.setFont(new java.awt.Font("Lucida Fax", 1, 18)); // NOI18N
        lblDivisaSaldo.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(4, 86, 160));

        lblDepositar.setFont(new java.awt.Font("Lucida Console", 1, 24)); // NOI18N
        lblDepositar.setForeground(new java.awt.Color(255, 255, 255));
        lblDepositar.setText("Depositar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDepositar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblDepositar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        lblAviso.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        lblAviso.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtras)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSaldoDisponible)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMonto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDivisaSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMontoADepositar)
                                        .addGap(102, 102, 102))
                                    .addComponent(jtfMonto))
                                .addGap(18, 18, 18)
                                .addComponent(lblDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(28, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDivisaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSaldoDisponible)
                    .addComponent(lblMonto))
                .addGap(66, 66, 66)
                .addComponent(lblMontoADepositar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtfMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDivisa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAtras, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDepositar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfMonto;
    private javax.swing.JLabel lblAviso;
    private javax.swing.JLabel lblDepositar;
    private javax.swing.JLabel lblDivisa;
    private javax.swing.JLabel lblDivisaSaldo;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblMontoADepositar;
    private javax.swing.JLabel lblSaldoDisponible;
    // End of variables declaration//GEN-END:variables
}
